"""Strategy Factory: candidate interfaces, alpha models, and evidence admission gates."""
from abc import ABC, abstractmethod
from dataclasses import dataclass, field
from enum import Enum
from typing import Dict, Any, List, Optional, Tuple

from .models import StrategySpec, StrategyStage, StrategyFamily, StrategyOrigin
from src.backtest.metrics import BacktestPerformanceReport


class SignalDirection(str, Enum):
    LONG = "LONG"
    SHORT = "SHORT"
    FLAT = "FLAT"


@dataclass
class Signal:
    """Standardized trade signal generated by an Alpha Model."""
    strategy_id: str
    symbol: str
    venue: str
    direction: SignalDirection
    target_weight: float  # Recommended fractional portfolio allocation [-1.0, 1.0]
    confidence: float     # [0.0, 1.0]
    expected_edge_bps: float
    ts_ns: int
    metadata: Dict[str, Any] = field(default_factory=dict)


class CandidateHypothesis(ABC):
    """Abstract interface for all candidate alpha models in the Strategy Factory."""

    def __init__(self, spec: StrategySpec):
        self.spec = spec

    @abstractmethod
    def generate_signal(self, market_data: Dict[str, Any], current_ts_ns: int) -> Optional[Signal]:
        """Evaluate point-in-time market state and produce trade signal."""
        pass


@dataclass
class EvidenceAdmissionGate:
    """Empirical hurdle criteria required to promote a strategy from RESEARCH to VALIDATION/HOLDOUT."""
    min_sharpe: float = 1.2
    max_drawdown_pct: float = 15.0
    min_profit_factor: float = 1.3
    min_expectancy_usd: float = 5.0
    min_trades: int = 30
    require_fdr_significance: bool = True

    def evaluate(self, report: BacktestPerformanceReport, is_fdr_significant: bool = True) -> Tuple[bool, List[str]]:
        """Strictly evaluate backtest performance report against admission gate."""
        reasons = []

        if report.annualized_sharpe < self.min_sharpe:
            reasons.append(f"Sharpe {report.annualized_sharpe:.2f} < required {self.min_sharpe:.2f}")
        if report.max_drawdown_pct > self.max_drawdown_pct:
            reasons.append(f"Max Drawdown {report.max_drawdown_pct:.1f}% > limit {self.max_drawdown_pct:.1f}%")
        if report.profit_factor < self.min_profit_factor:
            reasons.append(f"Profit Factor {report.profit_factor:.2f} < required {self.min_profit_factor:.2f}")
        if report.total_trades < self.min_trades:
            reasons.append(f"Total trades {report.total_trades} < required sample {self.min_trades}")
        if self.require_fdr_significance and not is_fdr_significant:
            reasons.append("Failed Benjamini-Hochberg False Discovery Rate multiple-testing hurdle.")

        passed = len(reasons) == 0
        return passed, reasons
