-- Trading / Quant OS control plane, migration 0001 (GENERATED by src/persistence/schema.py).
-- Do not edit by hand: tests/test_persistence_schema.py asserts this file equals the rendered output.
-- Soft references only (no FKs): rows arrive asynchronously through the outbox.

create or replace function public.forbid_mutation() returns trigger
language plpgsql as $$
begin
  raise exception 'table % is append-only: % not allowed', TG_TABLE_NAME, TG_OP;
end;
$$;

-- API/recorder process instances
create table if not exists public.system_instances (
  instance_id text primary key,
  git_sha text,
  mode text,
  started_at timestamptz,
  payload jsonb not null,
  synced_at timestamptz not null default now()
);
create index if not exists idx_system_instances_git_sha on public.system_instances (git_sha);
create index if not exists idx_system_instances_mode on public.system_instances (mode);
create index if not exists idx_system_instances_started_at on public.system_instances (started_at);
alter table public.system_instances enable row level security;
revoke all on public.system_instances from anon, authenticated;

-- Strategy inventory and lifecycle stage
create table if not exists public.strategy_registry (
  strategy_id text primary key,
  family text,
  origin text,
  stage text,
  economic_edge_validated boolean,
  payload jsonb not null,
  synced_at timestamptz not null default now()
);
create index if not exists idx_strategy_registry_family on public.strategy_registry (family);
create index if not exists idx_strategy_registry_origin on public.strategy_registry (origin);
create index if not exists idx_strategy_registry_stage on public.strategy_registry (stage);
create index if not exists idx_strategy_registry_economic_edge_validated on public.strategy_registry (economic_edge_validated);
alter table public.strategy_registry enable row level security;
revoke all on public.strategy_registry from anon, authenticated;

-- Immutable strategy version snapshots
create table if not exists public.strategy_versions (
  version_key text primary key,
  strategy_id text,
  strategy_version text,
  config_fingerprint text,
  payload jsonb not null,
  synced_at timestamptz not null default now()
);
create index if not exists idx_strategy_versions_strategy_id on public.strategy_versions (strategy_id);
create index if not exists idx_strategy_versions_strategy_version on public.strategy_versions (strategy_version);
create index if not exists idx_strategy_versions_config_fingerprint on public.strategy_versions (config_fingerprint);
alter table public.strategy_versions enable row level security;
revoke all on public.strategy_versions from anon, authenticated;
drop trigger if exists trg_strategy_versions_append_only on public.strategy_versions;
create trigger trg_strategy_versions_append_only before update or delete on public.strategy_versions for each row execute function public.forbid_mutation();

-- Rule provenance (INTUITION_UNVALIDATED ...)
create table if not exists public.strategy_rule_evidence (
  rule_key text primary key,
  strategy_id text,
  rule_id text,
  status text,
  payload jsonb not null,
  synced_at timestamptz not null default now()
);
create index if not exists idx_strategy_rule_evidence_strategy_id on public.strategy_rule_evidence (strategy_id);
create index if not exists idx_strategy_rule_evidence_rule_id on public.strategy_rule_evidence (rule_id);
create index if not exists idx_strategy_rule_evidence_status on public.strategy_rule_evidence (status);
alter table public.strategy_rule_evidence enable row level security;
revoke all on public.strategy_rule_evidence from anon, authenticated;

-- Counterparty thesis per strategy version
create table if not exists public.counterparty_theses (
  thesis_key text primary key,
  strategy_id text,
  strategy_version text,
  evidence_status text,
  payload jsonb not null,
  synced_at timestamptz not null default now()
);
create index if not exists idx_counterparty_theses_strategy_id on public.counterparty_theses (strategy_id);
create index if not exists idx_counterparty_theses_strategy_version on public.counterparty_theses (strategy_version);
create index if not exists idx_counterparty_theses_evidence_status on public.counterparty_theses (evidence_status);
alter table public.counterparty_theses enable row level security;
revoke all on public.counterparty_theses from anon, authenticated;

-- Every experiment incl. failures (trial accounting)
create table if not exists public.experiments (
  experiment_id text primary key,
  strategy_id text,
  strategy_version text,
  dataset_fingerprint text,
  config_fingerprint text,
  gate_result text,
  created_at timestamptz,
  payload jsonb not null,
  synced_at timestamptz not null default now()
);
create index if not exists idx_experiments_strategy_id on public.experiments (strategy_id);
create index if not exists idx_experiments_strategy_version on public.experiments (strategy_version);
create index if not exists idx_experiments_dataset_fingerprint on public.experiments (dataset_fingerprint);
create index if not exists idx_experiments_config_fingerprint on public.experiments (config_fingerprint);
create index if not exists idx_experiments_gate_result on public.experiments (gate_result);
create index if not exists idx_experiments_created_at on public.experiments (created_at);
alter table public.experiments enable row level security;
revoke all on public.experiments from anon, authenticated;
drop trigger if exists trg_experiments_append_only on public.experiments;
create trigger trg_experiments_append_only before update or delete on public.experiments for each row execute function public.forbid_mutation();

-- Metrics per experiment
create table if not exists public.experiment_metrics (
  metric_key text primary key,
  experiment_id text,
  payload jsonb not null,
  synced_at timestamptz not null default now()
);
create index if not exists idx_experiment_metrics_experiment_id on public.experiment_metrics (experiment_id);
alter table public.experiment_metrics enable row level security;
revoke all on public.experiment_metrics from anon, authenticated;
drop trigger if exists trg_experiment_metrics_append_only on public.experiment_metrics;
create trigger trg_experiment_metrics_append_only before update or delete on public.experiment_metrics for each row execute function public.forbid_mutation();

-- Artifacts produced by experiments
create table if not exists public.experiment_artifacts (
  artifact_id text primary key,
  experiment_id text,
  storage_path text,
  sha256 text,
  payload jsonb not null,
  synced_at timestamptz not null default now()
);
create index if not exists idx_experiment_artifacts_experiment_id on public.experiment_artifacts (experiment_id);
create index if not exists idx_experiment_artifacts_storage_path on public.experiment_artifacts (storage_path);
create index if not exists idx_experiment_artifacts_sha256 on public.experiment_artifacts (sha256);
alter table public.experiment_artifacts enable row level security;
revoke all on public.experiment_artifacts from anon, authenticated;
drop trigger if exists trg_experiment_artifacts_append_only on public.experiment_artifacts;
create trigger trg_experiment_artifacts_append_only before update or delete on public.experiment_artifacts for each row execute function public.forbid_mutation();

-- Sealed holdout dataset registrations
create table if not exists public.holdout_datasets (
  dataset_id text primary key,
  strategy_id text,
  dataset_fingerprint text,
  payload jsonb not null,
  synced_at timestamptz not null default now()
);
create index if not exists idx_holdout_datasets_strategy_id on public.holdout_datasets (strategy_id);
create index if not exists idx_holdout_datasets_dataset_fingerprint on public.holdout_datasets (dataset_fingerprint);
alter table public.holdout_datasets enable row level security;
revoke all on public.holdout_datasets from anon, authenticated;
drop trigger if exists trg_holdout_datasets_append_only on public.holdout_datasets;
create trigger trg_holdout_datasets_append_only before update or delete on public.holdout_datasets for each row execute function public.forbid_mutation();

-- Replica of holdout access audit
create table if not exists public.holdout_access_audit (
  audit_id text primary key,
  strategy_id text,
  strategy_version text,
  audit_hash text,
  opened_at timestamptz,
  payload jsonb not null,
  synced_at timestamptz not null default now()
);
create index if not exists idx_holdout_access_audit_strategy_id on public.holdout_access_audit (strategy_id);
create index if not exists idx_holdout_access_audit_strategy_version on public.holdout_access_audit (strategy_version);
create index if not exists idx_holdout_access_audit_audit_hash on public.holdout_access_audit (audit_hash);
create index if not exists idx_holdout_access_audit_opened_at on public.holdout_access_audit (opened_at);
alter table public.holdout_access_audit enable row level security;
revoke all on public.holdout_access_audit from anon, authenticated;
drop trigger if exists trg_holdout_access_audit_append_only on public.holdout_access_audit;
create trigger trg_holdout_access_audit_append_only before update or delete on public.holdout_access_audit for each row execute function public.forbid_mutation();

-- Auditable gate evaluations
create table if not exists public.strategy_gate_results (
  gate_result_id text primary key,
  strategy_id text,
  strategy_version text,
  gate_type text,
  status text,
  dataset_fingerprint text,
  config_fingerprint text,
  payload jsonb not null,
  synced_at timestamptz not null default now()
);
create index if not exists idx_strategy_gate_results_strategy_id on public.strategy_gate_results (strategy_id);
create index if not exists idx_strategy_gate_results_strategy_version on public.strategy_gate_results (strategy_version);
create index if not exists idx_strategy_gate_results_gate_type on public.strategy_gate_results (gate_type);
create index if not exists idx_strategy_gate_results_status on public.strategy_gate_results (status);
create index if not exists idx_strategy_gate_results_dataset_fingerprint on public.strategy_gate_results (dataset_fingerprint);
create index if not exists idx_strategy_gate_results_config_fingerprint on public.strategy_gate_results (config_fingerprint);
alter table public.strategy_gate_results enable row level security;
revoke all on public.strategy_gate_results from anon, authenticated;
drop trigger if exists trg_strategy_gate_results_append_only on public.strategy_gate_results;
create trigger trg_strategy_gate_results_append_only before update or delete on public.strategy_gate_results for each row execute function public.forbid_mutation();

-- Paper accounts
create table if not exists public.paper_accounts (
  paper_account_id text primary key,
  status text,
  data_source text,
  payload jsonb not null,
  synced_at timestamptz not null default now()
);
create index if not exists idx_paper_accounts_status on public.paper_accounts (status);
create index if not exists idx_paper_accounts_data_source on public.paper_accounts (data_source);
alter table public.paper_accounts enable row level security;
revoke all on public.paper_accounts from anon, authenticated;

-- Paper orders (status transitions idempotent)
create table if not exists public.paper_orders (
  order_id text primary key,
  paper_account_id text,
  strategy_id text,
  symbol text,
  status text,
  idempotency_key text,
  payload jsonb not null,
  synced_at timestamptz not null default now()
);
create index if not exists idx_paper_orders_paper_account_id on public.paper_orders (paper_account_id);
create index if not exists idx_paper_orders_strategy_id on public.paper_orders (strategy_id);
create index if not exists idx_paper_orders_symbol on public.paper_orders (symbol);
create index if not exists idx_paper_orders_status on public.paper_orders (status);
create index if not exists idx_paper_orders_idempotency_key on public.paper_orders (idempotency_key);
alter table public.paper_orders enable row level security;
revoke all on public.paper_orders from anon, authenticated;

-- Paper fills
create table if not exists public.paper_fills (
  fill_id text primary key,
  order_id text,
  paper_account_id text,
  symbol text,
  payload jsonb not null,
  synced_at timestamptz not null default now()
);
create index if not exists idx_paper_fills_order_id on public.paper_fills (order_id);
create index if not exists idx_paper_fills_paper_account_id on public.paper_fills (paper_account_id);
create index if not exists idx_paper_fills_symbol on public.paper_fills (symbol);
alter table public.paper_fills enable row level security;
revoke all on public.paper_fills from anon, authenticated;
drop trigger if exists trg_paper_fills_append_only on public.paper_fills;
create trigger trg_paper_fills_append_only before update or delete on public.paper_fills for each row execute function public.forbid_mutation();

-- Paper positions / snapshots
create table if not exists public.paper_positions (
  position_key text primary key,
  paper_account_id text,
  symbol text,
  payload jsonb not null,
  synced_at timestamptz not null default now()
);
create index if not exists idx_paper_positions_paper_account_id on public.paper_positions (paper_account_id);
create index if not exists idx_paper_positions_symbol on public.paper_positions (symbol);
alter table public.paper_positions enable row level security;
revoke all on public.paper_positions from anon, authenticated;

-- Deterministic risk decisions (approve/veto)
create table if not exists public.risk_decisions (
  decision_id text primary key,
  strategy_id text,
  symbol text,
  approved boolean,
  violation_code text,
  timestamp_utc timestamptz,
  payload jsonb not null,
  synced_at timestamptz not null default now()
);
create index if not exists idx_risk_decisions_strategy_id on public.risk_decisions (strategy_id);
create index if not exists idx_risk_decisions_symbol on public.risk_decisions (symbol);
create index if not exists idx_risk_decisions_approved on public.risk_decisions (approved);
create index if not exists idx_risk_decisions_violation_code on public.risk_decisions (violation_code);
create index if not exists idx_risk_decisions_timestamp_utc on public.risk_decisions (timestamp_utc);
alter table public.risk_decisions enable row level security;
revoke all on public.risk_decisions from anon, authenticated;
drop trigger if exists trg_risk_decisions_append_only on public.risk_decisions;
create trigger trg_risk_decisions_append_only before update or delete on public.risk_decisions for each row execute function public.forbid_mutation();

-- Risk events
create table if not exists public.risk_events (
  event_id text primary key,
  event_type text,
  strategy_id text,
  timestamp_utc timestamptz,
  payload jsonb not null,
  synced_at timestamptz not null default now()
);
create index if not exists idx_risk_events_event_type on public.risk_events (event_type);
create index if not exists idx_risk_events_strategy_id on public.risk_events (strategy_id);
create index if not exists idx_risk_events_timestamp_utc on public.risk_events (timestamp_utc);
alter table public.risk_events enable row level security;
revoke all on public.risk_events from anon, authenticated;
drop trigger if exists trg_risk_events_append_only on public.risk_events;
create trigger trg_risk_events_append_only before update or delete on public.risk_events for each row execute function public.forbid_mutation();

-- Kill switch activate/reset
create table if not exists public.kill_switch_events (
  event_id text primary key,
  action text,
  scope text,
  actor text,
  timestamp_utc timestamptz,
  payload jsonb not null,
  synced_at timestamptz not null default now()
);
create index if not exists idx_kill_switch_events_action on public.kill_switch_events (action);
create index if not exists idx_kill_switch_events_scope on public.kill_switch_events (scope);
create index if not exists idx_kill_switch_events_actor on public.kill_switch_events (actor);
create index if not exists idx_kill_switch_events_timestamp_utc on public.kill_switch_events (timestamp_utc);
alter table public.kill_switch_events enable row level security;
revoke all on public.kill_switch_events from anon, authenticated;
drop trigger if exists trg_kill_switch_events_append_only on public.kill_switch_events;
create trigger trg_kill_switch_events_append_only before update or delete on public.kill_switch_events for each row execute function public.forbid_mutation();

-- Capital pocket definitions/state
create table if not exists public.capital_pockets (
  capital_pocket_id text primary key,
  pocket_type text,
  state_kind text,
  authorized_live_capital_usd numeric,
  payload jsonb not null,
  synced_at timestamptz not null default now()
);
create index if not exists idx_capital_pockets_pocket_type on public.capital_pockets (pocket_type);
create index if not exists idx_capital_pockets_state_kind on public.capital_pockets (state_kind);
create index if not exists idx_capital_pockets_authorized_live_capital_usd on public.capital_pockets (authorized_live_capital_usd);
alter table public.capital_pockets enable row level security;
revoke all on public.capital_pockets from anon, authenticated;

-- Prop firm rule profiles
create table if not exists public.prop_rule_profiles (
  profile_key text primary key,
  provider_id text,
  profile_version text,
  verification_status text,
  evidence_fingerprint text,
  payload jsonb not null,
  synced_at timestamptz not null default now()
);
create index if not exists idx_prop_rule_profiles_provider_id on public.prop_rule_profiles (provider_id);
create index if not exists idx_prop_rule_profiles_profile_version on public.prop_rule_profiles (profile_version);
create index if not exists idx_prop_rule_profiles_verification_status on public.prop_rule_profiles (verification_status);
create index if not exists idx_prop_rule_profiles_evidence_fingerprint on public.prop_rule_profiles (evidence_fingerprint);
alter table public.prop_rule_profiles enable row level security;
revoke all on public.prop_rule_profiles from anon, authenticated;

-- Evidence backing prop profiles
create table if not exists public.prop_profile_evidence (
  evidence_id text primary key,
  provider_id text,
  profile_version text,
  evidence_fingerprint text,
  payload jsonb not null,
  synced_at timestamptz not null default now()
);
create index if not exists idx_prop_profile_evidence_provider_id on public.prop_profile_evidence (provider_id);
create index if not exists idx_prop_profile_evidence_profile_version on public.prop_profile_evidence (profile_version);
create index if not exists idx_prop_profile_evidence_evidence_fingerprint on public.prop_profile_evidence (evidence_fingerprint);
alter table public.prop_profile_evidence enable row level security;
revoke all on public.prop_profile_evidence from anon, authenticated;
drop trigger if exists trg_prop_profile_evidence_append_only on public.prop_profile_evidence;
create trigger trg_prop_profile_evidence_append_only before update or delete on public.prop_profile_evidence for each row execute function public.forbid_mutation();

-- Prop exam attempts
create table if not exists public.prop_exam_attempts (
  attempt_id text primary key,
  strategy_id text,
  strategy_version text,
  provider_id text,
  profile_version text,
  passed boolean,
  payload jsonb not null,
  synced_at timestamptz not null default now()
);
create index if not exists idx_prop_exam_attempts_strategy_id on public.prop_exam_attempts (strategy_id);
create index if not exists idx_prop_exam_attempts_strategy_version on public.prop_exam_attempts (strategy_version);
create index if not exists idx_prop_exam_attempts_provider_id on public.prop_exam_attempts (provider_id);
create index if not exists idx_prop_exam_attempts_profile_version on public.prop_exam_attempts (profile_version);
create index if not exists idx_prop_exam_attempts_passed on public.prop_exam_attempts (passed);
alter table public.prop_exam_attempts enable row level security;
revoke all on public.prop_exam_attempts from anon, authenticated;
drop trigger if exists trg_prop_exam_attempts_append_only on public.prop_exam_attempts;
create trigger trg_prop_exam_attempts_append_only before update or delete on public.prop_exam_attempts for each row execute function public.forbid_mutation();

-- Prop exam Monte Carlo results
create table if not exists public.prop_exam_simulations (
  simulation_id text primary key,
  strategy_id text,
  provider_id text,
  profile_version text,
  status text,
  payload jsonb not null,
  synced_at timestamptz not null default now()
);
create index if not exists idx_prop_exam_simulations_strategy_id on public.prop_exam_simulations (strategy_id);
create index if not exists idx_prop_exam_simulations_provider_id on public.prop_exam_simulations (provider_id);
create index if not exists idx_prop_exam_simulations_profile_version on public.prop_exam_simulations (profile_version);
create index if not exists idx_prop_exam_simulations_status on public.prop_exam_simulations (status);
alter table public.prop_exam_simulations enable row level security;
revoke all on public.prop_exam_simulations from anon, authenticated;
drop trigger if exists trg_prop_exam_simulations_append_only on public.prop_exam_simulations;
create trigger trg_prop_exam_simulations_append_only before update or delete on public.prop_exam_simulations for each row execute function public.forbid_mutation();

-- Written multi-account evidence
create table if not exists public.multi_account_evidence (
  evidence_id text primary key,
  provider_name text,
  account_id text,
  payload jsonb not null,
  synced_at timestamptz not null default now()
);
create index if not exists idx_multi_account_evidence_provider_name on public.multi_account_evidence (provider_name);
create index if not exists idx_multi_account_evidence_account_id on public.multi_account_evidence (account_id);
alter table public.multi_account_evidence enable row level security;
revoke all on public.multi_account_evidence from anon, authenticated;
drop trigger if exists trg_multi_account_evidence_append_only on public.multi_account_evidence;
create trigger trg_multi_account_evidence_append_only before update or delete on public.multi_account_evidence for each row execute function public.forbid_mutation();

-- EventCluster definitions
create table if not exists public.event_clusters (
  cluster_id text primary key,
  description text,
  payload jsonb not null,
  synced_at timestamptz not null default now()
);
create index if not exists idx_event_clusters_description on public.event_clusters (description);
alter table public.event_clusters enable row level security;
revoke all on public.event_clusters from anon, authenticated;

-- Append-oriented audit trail (hash chained)
create table if not exists public.audit_events (
  audit_id text primary key,
  event_type text,
  entity_type text,
  entity_id text,
  timestamp_utc timestamptz,
  chain_hash text,
  payload jsonb not null,
  synced_at timestamptz not null default now()
);
create index if not exists idx_audit_events_event_type on public.audit_events (event_type);
create index if not exists idx_audit_events_entity_type on public.audit_events (entity_type);
create index if not exists idx_audit_events_entity_id on public.audit_events (entity_id);
create index if not exists idx_audit_events_timestamp_utc on public.audit_events (timestamp_utc);
create index if not exists idx_audit_events_chain_hash on public.audit_events (chain_hash);
alter table public.audit_events enable row level security;
revoke all on public.audit_events from anon, authenticated;
drop trigger if exists trg_audit_events_append_only on public.audit_events;
create trigger trg_audit_events_append_only before update or delete on public.audit_events for each row execute function public.forbid_mutation();

-- Catalog of every immutable Parquet part
create table if not exists public.market_data_files (
  file_id text primary key,
  run_id text,
  venue text,
  table_name text,
  symbol text,
  partition_year integer,
  partition_month integer,
  partition_day integer,
  partition_hour integer,
  local_path text,
  storage_path text,
  row_count bigint,
  byte_size bigint,
  min_event_timestamp timestamptz,
  max_event_timestamp timestamptz,
  sha256 text,
  manifest_sha256 text,
  upload_status text,
  created_at timestamptz,
  uploaded_at timestamptz,
  retry_count integer,
  last_error text,
  config_fingerprint text,
  payload jsonb not null,
  synced_at timestamptz not null default now()
);
create index if not exists idx_market_data_files_run_id on public.market_data_files (run_id);
create index if not exists idx_market_data_files_venue on public.market_data_files (venue);
create index if not exists idx_market_data_files_table_name on public.market_data_files (table_name);
create index if not exists idx_market_data_files_symbol on public.market_data_files (symbol);
create index if not exists idx_market_data_files_partition_year on public.market_data_files (partition_year);
create index if not exists idx_market_data_files_partition_month on public.market_data_files (partition_month);
create index if not exists idx_market_data_files_partition_day on public.market_data_files (partition_day);
create index if not exists idx_market_data_files_partition_hour on public.market_data_files (partition_hour);
create index if not exists idx_market_data_files_local_path on public.market_data_files (local_path);
create index if not exists idx_market_data_files_storage_path on public.market_data_files (storage_path);
create index if not exists idx_market_data_files_row_count on public.market_data_files (row_count);
create index if not exists idx_market_data_files_byte_size on public.market_data_files (byte_size);
create index if not exists idx_market_data_files_min_event_timestamp on public.market_data_files (min_event_timestamp);
create index if not exists idx_market_data_files_max_event_timestamp on public.market_data_files (max_event_timestamp);
create index if not exists idx_market_data_files_sha256 on public.market_data_files (sha256);
create index if not exists idx_market_data_files_manifest_sha256 on public.market_data_files (manifest_sha256);
create index if not exists idx_market_data_files_upload_status on public.market_data_files (upload_status);
create index if not exists idx_market_data_files_created_at on public.market_data_files (created_at);
create index if not exists idx_market_data_files_uploaded_at on public.market_data_files (uploaded_at);
create index if not exists idx_market_data_files_retry_count on public.market_data_files (retry_count);
create index if not exists idx_market_data_files_last_error on public.market_data_files (last_error);
create index if not exists idx_market_data_files_config_fingerprint on public.market_data_files (config_fingerprint);
alter table public.market_data_files enable row level security;
revoke all on public.market_data_files from anon, authenticated;

-- Research dataset registrations
create table if not exists public.research_datasets (
  dataset_id text primary key,
  dataset_fingerprint text,
  config_fingerprint text,
  storage_path text,
  payload jsonb not null,
  synced_at timestamptz not null default now()
);
create index if not exists idx_research_datasets_dataset_fingerprint on public.research_datasets (dataset_fingerprint);
create index if not exists idx_research_datasets_config_fingerprint on public.research_datasets (config_fingerprint);
create index if not exists idx_research_datasets_storage_path on public.research_datasets (storage_path);
alter table public.research_datasets enable row level security;
revoke all on public.research_datasets from anon, authenticated;
drop trigger if exists trg_research_datasets_append_only on public.research_datasets;
create trigger trg_research_datasets_append_only before update or delete on public.research_datasets for each row execute function public.forbid_mutation();

-- Backtest/model/report artifacts
create table if not exists public.research_artifacts (
  artifact_id text primary key,
  artifact_type text,
  sha256 text,
  storage_path text,
  payload jsonb not null,
  synced_at timestamptz not null default now()
);
create index if not exists idx_research_artifacts_artifact_type on public.research_artifacts (artifact_type);
create index if not exists idx_research_artifacts_sha256 on public.research_artifacts (sha256);
create index if not exists idx_research_artifacts_storage_path on public.research_artifacts (storage_path);
alter table public.research_artifacts enable row level security;
revoke all on public.research_artifacts from anon, authenticated;
drop trigger if exists trg_research_artifacts_append_only on public.research_artifacts;
create trigger trg_research_artifacts_append_only before update or delete on public.research_artifacts for each row execute function public.forbid_mutation();

-- Versioned configuration snapshots
create table if not exists public.configuration_snapshots (
  snapshot_id text primary key,
  config_kind text,
  config_fingerprint text,
  created_at timestamptz,
  payload jsonb not null,
  synced_at timestamptz not null default now()
);
create index if not exists idx_configuration_snapshots_config_kind on public.configuration_snapshots (config_kind);
create index if not exists idx_configuration_snapshots_config_fingerprint on public.configuration_snapshots (config_fingerprint);
create index if not exists idx_configuration_snapshots_created_at on public.configuration_snapshots (created_at);
alter table public.configuration_snapshots enable row level security;
revoke all on public.configuration_snapshots from anon, authenticated;
drop trigger if exists trg_configuration_snapshots_append_only on public.configuration_snapshots;
create trigger trg_configuration_snapshots_append_only before update or delete on public.configuration_snapshots for each row execute function public.forbid_mutation();

-- Canonical OrderIntents (immutable evidence)
create table if not exists public.execution_intents (
  intent_id text primary key,
  strategy_id text,
  venue text,
  symbol text,
  idempotency_key text,
  client_order_id text,
  execution_mode text,
  created_at timestamptz,
  payload jsonb not null,
  synced_at timestamptz not null default now()
);
create index if not exists idx_execution_intents_strategy_id on public.execution_intents (strategy_id);
create index if not exists idx_execution_intents_venue on public.execution_intents (venue);
create index if not exists idx_execution_intents_symbol on public.execution_intents (symbol);
create index if not exists idx_execution_intents_idempotency_key on public.execution_intents (idempotency_key);
create index if not exists idx_execution_intents_client_order_id on public.execution_intents (client_order_id);
create index if not exists idx_execution_intents_execution_mode on public.execution_intents (execution_mode);
create index if not exists idx_execution_intents_created_at on public.execution_intents (created_at);
alter table public.execution_intents enable row level security;
revoke all on public.execution_intents from anon, authenticated;
drop trigger if exists trg_execution_intents_append_only on public.execution_intents;
create trigger trg_execution_intents_append_only before update or delete on public.execution_intents for each row execute function public.forbid_mutation();

-- Current order lifecycle state (mutable projection)
create table if not exists public.execution_orders (
  intent_id text primary key,
  client_order_id text,
  venue_order_id text,
  venue text,
  symbol text,
  state text,
  idempotency_key text,
  payload jsonb not null,
  synced_at timestamptz not null default now()
);
create index if not exists idx_execution_orders_client_order_id on public.execution_orders (client_order_id);
create index if not exists idx_execution_orders_venue_order_id on public.execution_orders (venue_order_id);
create index if not exists idx_execution_orders_venue on public.execution_orders (venue);
create index if not exists idx_execution_orders_symbol on public.execution_orders (symbol);
create index if not exists idx_execution_orders_state on public.execution_orders (state);
create index if not exists idx_execution_orders_idempotency_key on public.execution_orders (idempotency_key);
alter table public.execution_orders enable row level security;
revoke all on public.execution_orders from anon, authenticated;

-- Every submission attempt (written BEFORE transmission)
create table if not exists public.execution_attempts (
  attempt_id text primary key,
  intent_id text,
  client_order_id text,
  venue text,
  attempt_no text,
  outcome text,
  started_at timestamptz,
  payload jsonb not null,
  synced_at timestamptz not null default now()
);
create index if not exists idx_execution_attempts_intent_id on public.execution_attempts (intent_id);
create index if not exists idx_execution_attempts_client_order_id on public.execution_attempts (client_order_id);
create index if not exists idx_execution_attempts_venue on public.execution_attempts (venue);
create index if not exists idx_execution_attempts_attempt_no on public.execution_attempts (attempt_no);
create index if not exists idx_execution_attempts_outcome on public.execution_attempts (outcome);
create index if not exists idx_execution_attempts_started_at on public.execution_attempts (started_at);
alter table public.execution_attempts enable row level security;
revoke all on public.execution_attempts from anon, authenticated;
drop trigger if exists trg_execution_attempts_append_only on public.execution_attempts;
create trigger trg_execution_attempts_append_only before update or delete on public.execution_attempts for each row execute function public.forbid_mutation();

-- Order state machine transitions
create table if not exists public.order_state_transitions (
  transition_id text primary key,
  intent_id text,
  from_state text,
  to_state text,
  at timestamptz,
  payload jsonb not null,
  synced_at timestamptz not null default now()
);
create index if not exists idx_order_state_transitions_intent_id on public.order_state_transitions (intent_id);
create index if not exists idx_order_state_transitions_from_state on public.order_state_transitions (from_state);
create index if not exists idx_order_state_transitions_to_state on public.order_state_transitions (to_state);
create index if not exists idx_order_state_transitions_at on public.order_state_transitions (at);
alter table public.order_state_transitions enable row level security;
revoke all on public.order_state_transitions from anon, authenticated;
drop trigger if exists trg_order_state_transitions_append_only on public.order_state_transitions;
create trigger trg_order_state_transitions_append_only before update or delete on public.order_state_transitions for each row execute function public.forbid_mutation();

-- Normalized fills incl. partials and fees
create table if not exists public.execution_fills (
  fill_id text primary key,
  intent_id text,
  venue text,
  venue_trade_id text,
  payload jsonb not null,
  synced_at timestamptz not null default now()
);
create index if not exists idx_execution_fills_intent_id on public.execution_fills (intent_id);
create index if not exists idx_execution_fills_venue on public.execution_fills (venue);
create index if not exists idx_execution_fills_venue_trade_id on public.execution_fills (venue_trade_id);
alter table public.execution_fills enable row level security;
revoke all on public.execution_fills from anon, authenticated;
drop trigger if exists trg_execution_fills_append_only on public.execution_fills;
create trigger trg_execution_fills_append_only before update or delete on public.execution_fills for each row execute function public.forbid_mutation();

-- Reconciliation evidence
create table if not exists public.reconciliation_events (
  event_id text primary key,
  venue text,
  status text,
  at timestamptz,
  payload jsonb not null,
  synced_at timestamptz not null default now()
);
create index if not exists idx_reconciliation_events_venue on public.reconciliation_events (venue);
create index if not exists idx_reconciliation_events_status on public.reconciliation_events (status);
create index if not exists idx_reconciliation_events_at on public.reconciliation_events (at);
alter table public.reconciliation_events enable row level security;
revoke all on public.reconciliation_events from anon, authenticated;
drop trigger if exists trg_reconciliation_events_append_only on public.reconciliation_events;
create trigger trg_reconciliation_events_append_only before update or delete on public.reconciliation_events for each row execute function public.forbid_mutation();

-- Connection/private-stream/clock events
create table if not exists public.connection_events (
  event_id text primary key,
  venue text,
  event_type text,
  at timestamptz,
  payload jsonb not null,
  synced_at timestamptz not null default now()
);
create index if not exists idx_connection_events_venue on public.connection_events (venue);
create index if not exists idx_connection_events_event_type on public.connection_events (event_type);
create index if not exists idx_connection_events_at on public.connection_events (at);
alter table public.connection_events enable row level security;
revoke all on public.connection_events from anon, authenticated;
drop trigger if exists trg_connection_events_append_only on public.connection_events;
create trigger trg_connection_events_append_only before update or delete on public.connection_events for each row execute function public.forbid_mutation();

-- Rate-limit telemetry
create table if not exists public.rate_limit_events (
  event_id text primary key,
  venue text,
  event_type text,
  at timestamptz,
  payload jsonb not null,
  synced_at timestamptz not null default now()
);
create index if not exists idx_rate_limit_events_venue on public.rate_limit_events (venue);
create index if not exists idx_rate_limit_events_event_type on public.rate_limit_events (event_type);
create index if not exists idx_rate_limit_events_at on public.rate_limit_events (at);
alter table public.rate_limit_events enable row level security;
revoke all on public.rate_limit_events from anon, authenticated;
drop trigger if exists trg_rate_limit_events_append_only on public.rate_limit_events;
create trigger trg_rate_limit_events_append_only before update or delete on public.rate_limit_events for each row execute function public.forbid_mutation();

-- Execution latency traces
create table if not exists public.latency_samples (
  sample_id text primary key,
  intent_id text,
  venue text,
  payload jsonb not null,
  synced_at timestamptz not null default now()
);
create index if not exists idx_latency_samples_intent_id on public.latency_samples (intent_id);
create index if not exists idx_latency_samples_venue on public.latency_samples (venue);
alter table public.latency_samples enable row level security;
revoke all on public.latency_samples from anon, authenticated;
drop trigger if exists trg_latency_samples_append_only on public.latency_samples;
create trigger trg_latency_samples_append_only before update or delete on public.latency_samples for each row execute function public.forbid_mutation();

-- Normalized account snapshots
create table if not exists public.account_snapshots (
  snapshot_id text primary key,
  venue text,
  account_id text,
  status text,
  at timestamptz,
  payload jsonb not null,
  synced_at timestamptz not null default now()
);
create index if not exists idx_account_snapshots_venue on public.account_snapshots (venue);
create index if not exists idx_account_snapshots_account_id on public.account_snapshots (account_id);
create index if not exists idx_account_snapshots_status on public.account_snapshots (status);
create index if not exists idx_account_snapshots_at on public.account_snapshots (at);
alter table public.account_snapshots enable row level security;
revoke all on public.account_snapshots from anon, authenticated;
drop trigger if exists trg_account_snapshots_append_only on public.account_snapshots;
create trigger trg_account_snapshots_append_only before update or delete on public.account_snapshots for each row execute function public.forbid_mutation();
