-- Trading / Quant OS control plane, migration 0002 (GENERATED by src/persistence/schema.py).
-- Safe schema migration: adds data_hash column to all mutable control-plane tables.
-- PostgREST conditional PATCH uses data_hash for atomic CAS updates without RPC.

alter table if exists public.system_instances add column if not exists data_hash text;
alter table if exists public.strategy_registry add column if not exists data_hash text;
alter table if exists public.strategy_rule_evidence add column if not exists data_hash text;
alter table if exists public.counterparty_theses add column if not exists data_hash text;
alter table if exists public.paper_accounts add column if not exists data_hash text;
alter table if exists public.paper_orders add column if not exists data_hash text;
alter table if exists public.paper_positions add column if not exists data_hash text;
alter table if exists public.capital_pockets add column if not exists data_hash text;
alter table if exists public.prop_rule_profiles add column if not exists data_hash text;
alter table if exists public.event_clusters add column if not exists data_hash text;
alter table if exists public.market_data_files add column if not exists data_hash text;
alter table if exists public.execution_orders add column if not exists data_hash text;
